---
- name: Install openstack-client from package.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ openstack_client_package_name }}"
  environment: "{{ proxy_env | default(omit) }}"
