---
- name: Define openstack_client_build_depends.
  set_fact:
    openstack_client_build_depends: "{{ __openstack_client_build_depends | list }}"
  when: openstack_client_build_depends is not defined

- name: Ensure build dependencies are installed.
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ openstack_client_build_depends }}"
  when: openstack_client_install_method == 'curl' or openstack_client_install_method == 'pip'

- include: "install/{{ openstack_client_install_method }}.yaml"
  when: not ansible_check_mode
